"""Pydantic contracts for the Model Planning Agent (SP5)."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

from mlops_agents.contracts.training import TrainingPlan

PlannerStatus = Literal["ok", "retry_ok", "failed"]


class EvidenceReference(BaseModel):
    """Reference to evidence used in planning decision."""

    source: Literal[
        "dataset_profile",
        "task_metadata",
        "experience",
        "rule",
        "registry",
    ]
    source_id: str | None = None
    summary: str


class CandidateResultCompact(BaseModel):
    """Compact representation of a model candidate's training result."""

    model_key: str
    rank: int
    metric_value: float | None = None


class ExperienceSummary(BaseModel):
    """Summary of a similar past task experience."""

    experience_id: str
    similarity_score: float
    dataset_summary: str
    models_trained: list[str]
    best_model: str
    validation_score: float
    candidate_results: list[CandidateResultCompact] = Field(default_factory=list)
    notes: str = ""


class PlannerContext(BaseModel):
    """Input context for the planner agent."""

    current_dataset_profile: dict[str, str | int | float | bool]
    task_metadata: dict[str, str | int | float | bool]
    available_models: list[str]
    similar_experiences: list[ExperienceSummary]
    matched_rules: list[dict[str, str | int | float | bool | list[str] | dict[str, Any]]]


class PlannerOutput(BaseModel):
    """Output from the Model Planning Agent (SP5)."""

    planning_analysis: str = Field(
        description=(
            "Detailed public analysis generated by the LLM. "
            "This is an explanation artifact — not guaranteed access to "
            "the model's internal reasoning process."
        )
    )
    evidence_used: list[EvidenceReference] = Field(default_factory=list)
    risks_or_warnings: list[str] = Field(default_factory=list)
    plan: TrainingPlan
