"""Pydantic contracts for the Model Planning Agent (SP5)."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

from mlops_agents.contracts.evidence import EvidenceReference
from mlops_agents.contracts.training import (
    CandidateSpec,
    PlannerTrainingPlan,
    RejectedModelSpec,
)

# Re-export for consumers that import from planner
# (PlannerValidationContext moved to planning/context.py — it carries domain
# objects (ModelSpec), and contracts/ must stay free of domain imports.)
__all__ = [
    "CandidateSpec",
    "RejectedModelSpec",
    "DecisionBasis",
    "EvidenceConflict",
    "EvidenceReference",
    "CandidateResultCompact",
    "ExperienceSummary",
    "PlannerContext",
    "PlannerOutput",
]

PlannerStatus = Literal["ok", "retry_ok", "failed"]


class CandidateResultCompact(BaseModel):
    """Compact representation of a model candidate's training result."""

    model_key: str
    rank: int
    metric_value: float | None = None


class DecisionBasis(BaseModel):
    """Structured rationale for the planner's overall strategy."""

    primary_evidence: list[EvidenceReference] = Field(min_length=1)
    secondary_evidence: list[EvidenceReference] = Field(default_factory=list)
    final_strategy: str = Field(min_length=1)


class EvidenceConflict(BaseModel):
    """A detected conflict between two or more evidence sources."""

    summary: str = Field(min_length=1)
    affected_models: list[str] = Field(min_length=1)
    conflicting_evidence_refs: list[EvidenceReference] = Field(min_length=1)
    resolution: str = Field(min_length=1)


class ExperienceSummary(BaseModel):
    """Summary of a similar past task experience."""

    experience_id: str
    similarity_score: float
    relevance_tier: Literal["high", "medium", "low"]
    matched_buckets: list[str] = Field(default_factory=list)
    mismatched_buckets: list[str] = Field(default_factory=list)
    target_scale_note: str | None = None
    dataset_summary: str
    models_trained: list[str]
    best_model: str
    validation_score: float
    metric_name: str | None = None
    candidate_results: list[CandidateResultCompact] = Field(default_factory=list)
    notes: str = ""


class PlannerContext(BaseModel):
    """Input context for the planner agent."""

    current_dataset_profile: dict[str, Any]
    task_metadata: dict[str, Any]
    available_models: list[str]
    similar_experiences: list[ExperienceSummary]
    matched_rules: list[dict[str, Any]]


class PlannerOutput(BaseModel):
    """Output from the Model Planning Agent (SP5)."""

    planning_analysis: str = Field(
        description=(
            "Detailed public analysis generated by the LLM. "
            "This is an explanation artifact — not guaranteed access to "
            "the model's internal reasoning process."
        )
    )
    # Optional: downstream consumers (planner_node, validation) handle its absence.
    decision_basis: DecisionBasis | None = None
    evidence_used: list[EvidenceReference] = Field(default_factory=list)
    evidence_conflicts: list[EvidenceConflict] = Field(default_factory=list)
    risks_or_warnings: list[str] = Field(default_factory=list)
    plan: PlannerTrainingPlan
